version: '3'

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - ./drupal/custom_theme:/var/www/html/themes/custom/custom_theme
    depends_on:
      - database
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_HOST: database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

